version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/storage:/app/storage  
    environment:
      - FLASK_ENV=production
    depends_on:
      - database
    restart: unless-stopped  # ✅ Evita reinicios infinitos si falla

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: plataforma_educativa_q0m3_user
      POSTGRES_PASSWORD: JrQTAVhQpK1I0q84Jba6JLYWsZiD9IMu
      POSTGRES_DB: plataforma_educativa_q0m3
    ports:
      - "5432:5432"
    restart: always
