name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker
        run: docker-compose up --build -d

      - name: Verificar que Flask está corriendo
        run: curl --retry 10 --retry-delay 5 -f http://localhost:5000 || exit 1

      - name: Verificar que React está corriendo
        run: curl --retry 10 --retry-delay 5 -f http://localhost:3000 || exit 1
