name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Construir y levantar los contenedores
        run: |
          docker-compose down || true  # Asegurar que no hay contenedores en ejecución
          docker-compose up --build -d  # Construir y levantar los contenedores

      - name: Esperar a que Flask esté listo
        run: |
          echo "Esperando a que Flask esté disponible..."
          sleep 15  # Esperar 15 segundos antes de hacer la verificación
          curl --retry 10 --retry-delay 5 -f http://localhost:5000 || exit 1

      - name: Verificar que React está corriendo
        run: curl --retry 10 --retry-delay 5 -f http://localhost:3000 || exit 1

      - name: Detener contenedores después de la prueba
        run: docker-compose down
